# Generated by Django 5.0.7 on 2024-07-22 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="slug",
        ),
        migrations.AddField(
            model_name="todo",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="todo.category",
            ),
        ),
        migrations.AddField(
            model_name="todo",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
