# Generated by Django 5.0.7 on 2024-07-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0004_remove_todo_slug_todo_category_todo_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
