# Generated by Django 5.0.7 on 2024-07-23 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0009_tag_todo_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="tag",
        ),
    ]
