# Generated by Django 5.0.7 on 2024-07-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0010_remove_todo_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="tag",
            field=models.ManyToManyField(to="todo.tag"),
        ),
    ]
